main:
        hosts:
                bastion-a.example.net:
                        ansible_host: 192.168.1.10
                        ansible_user: ubuntu
                        bastion:
                                name: z1
                                role: main
                                version: v3.02.00
replica:
        hosts:
                bastion-b.example.net:
                        ansible_host: 192.168.1.11
                        ansible_user: ubuntu
                        bastion:
                                name: z1
                                role: replica
                                version: v3.02.00
                                replicates: 192.168.1.10,{add your ipv6 if available}
